services:
  app:
    build: .
    restart: on-failure:3
    network_mode: bridge
    image: delete-user-in-channels-bot
    volumes:
      - ./${DATABASE_NAME}:/app/${DATABASE_NAME}
    working_dir: /app

  database_migration_file:
    profiles: [ "migration" ]

    build: .

    image: delete-user-in-channels-bot

    network_mode: bridge

    env_file:
      - ${ENV_FILE}

    volumes:
      - ./:/app/

    command: ["alembic", "upgrade", "head"]